objectifs:
  - bénéficiaire . dividendes . versés
  - bénéficiaire . dividendes . nets d'impôt
unité par défaut: €
situation:
  entreprise . imposition: "'IS'"
  # dirigeant: "'assimilé salarié'" [XXX] essayer de mettre ça par défaut pour voir
# [XXX] questions à l'affiche and co?
questions:
  à l'affiche:
    Régime social du dirigeant: dirigeant
